package com.mgm_tp.atlas.jira.udc.helper

enum GenerateDataOptions {
    PROJECT_LEAD_PERMISSION("PROJECT_LEAD_PERMISSION"),
    COMPONENT_LEAD_PERMISSION("COMPONENT_LEAD_PERMISSION"),
    PRIVATE_DASHBOARD("PRIVATE_DASHBOARD"),
    SHARED_DASHBOARD("SHARED_DASHBOARD"),
    PRIVATE_FILTER("PRIVATE_FILTER"),
    SHARED_FILTER("SHARED_FILTER"),
    PRIVATE_AGILEBOARD("PRIVATE_AGILEBOARD"),
    SHARED_AGILEBOARD("SHARED_AGILEBOARD"),
    PERMITTED_FILTER("PERMITTED_FILTER"),
    PERMITTED_DASHBOARD("PERMITTED_DASHBOARD"),
    PERMITTED_AGILEBOARD("PERMITTED_AGILEBOARD"),
    PERSONAL_SUBSCRIBED_FILTER("PERSONAL_SUBSCRIBED_FILTER"),
    GROUP_SUBSCRIBED_FILTER("GROUP_SUBSCRIBED_FILTER"),
    PROJECT_PERMISSION_ROLE("PROJECT_PERMISSION_ROLE"),
    CF_USER_DEFAULT_CONTEXT("CF_USER_DEFAULT_CONTEXT"),
    PERMISSION_SCHEME("PERMISSION_SCHEME"),
    NOTIFICATION_SCHEME("NOTIFICATION_SCHEME"),
    ISSUE_SECURITY_SCHEME("ISSUE_SECURITY_SCHEME"),
    AVATAR("AVATAR"),
    PERSONAL_ACCESS_TOKEN("PERSONAL_ACCESS_TOKEN"),
    REMEMBER_ME_TOKEN("REMEMBER_ME_TOKEN"),
    GROUPS("GROUPS"),

    final String option

    // Constructor to assign the display name
    GenerateDataOptions(String option) {
        this.option = option
    }

    // Override toString() to return the display name
    String toString() {
        option
    }
}